{% set name = "HiGHS" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d10175ad66e7f113ac5dc00c9d6650a620663a6884fbf2942d6eb7a3d854604f

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/highs/Highs.h  # [unix]
    - test -f ${PREFIX}/lib/libhighs.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)  # [win]

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://highs.dev
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - julian-belina
    - DerThorsten
